### ISSUE TITLE
So I dare you, Smilo Blockchain

### ISSUE THREAD

**Issue by thomasmodeneis** [pokusio/le-defi#3]
## Complete automated startup script:
https://github.com/smilofoundation/smilo-tools

## Complete automated kubernetes integration:
https://github.com/smilofoundation/kubernetes-smilo

## Smilo consists of mainly two components:
1. Blockchain
https://github.com/smilofoundation/go-smilo
2. Blackbox:
https://github.com/smilofoundation/Smilo-blackbox

## Website:
https://www.smilo.foundation/

## Wiki:
https://github.com/smilofoundation/Wiki/wiki

## Links and resources:
https://github.com/smilofoundation/Wiki/wiki/Awesome-Smilo---Links-and-resources

## Using Smilo with Ubuntu:
https://medium.com/@smilofoundation/installing-smilo-mainnet-node-on-ubuntu-linux-485023afd061

**Comment by Jean-Baptiste-Lasselle** [comment]
Oh, so thank you @thomasmodeneis :D ! I will try that as soon as possible, and make a full neat report in amrkdown! you are the first person to chalenge, that's exciting, thank you so much for taking the time to ! :)

**Comment by Jean-Baptiste-Lasselle** [comment]
## Complete automated startup script:

About https://github.com/smilofoundation/smilo-tools as far as I could read : 
> 
> * In this Performance test demo, we are using Graphana and smilo-tools to generate and submit transactions to a smilo blockchain private cluster of 7 nodes.
> 

So ok, let's dive right now into it a first  time : 
* provision the private blockchain : 
> 
> Hardware used is; 5 Masternodes, Xeon 2670 - 32 GB. => there I will try with 5 small VMs, and I will see if
>  the installation fails to complete, but I am first interested in testing if it will fail, and just make the
>  blockchain still available in "degraded" mode
> 
* If it has too, I have 10 64 Gb Xeon servers HP DL 360 Generation 5, plus 3 DELL PowerEdge R610  4 Xeon CPUs, should do
  * https://github.com/smilofoundation/smilo-tools : inside there i found no docuementation to help me actiually provision the private blockchain
* Alright, next steps : (swtiched to https://medium.com/@smilofoundation/installing-smilo-mainnet-node-on-ubuntu-linux-485023afd061 )
  * oh i see, you do not have any dockerized stack, for your smilo @thomasmodeneis  ? Or have you (a link to docker doc of smilo maybe..) ? 
  * in https://github.com/smilofoundation/Wiki/wiki I cannot find any page where the provisioning process for the example 7 Machines is described... @thomasmodeneis ...Could you provide a speicific link to a specific page, where I can read "How to install Private Smilo Blockchain", smthg like that ...?
  * Ok, now my hopes are going down @thomasmodeneis : in https://github.com/smilofoundation/go-smilo I cannot find anywhere, where it would explain how to install a private full Blockchain ... Plus here make this clear to me : 
    * what do you mean by  _**Fast node on the main Smilo SPoRT network**_  , and what  is the _**the main Smilo SPoRT network**_ in this sentence...?  It is a blockchain operated by someone else, isn't it ? I will wait for your answer in that one before going further or saying further. 


hum now I found https://github.com/smilofoundation/kubernetes-smilo#create-smilo-deployment  though i do not understand how to use smilo-tools

so great, as you might have seen i use `k3d` so will quickly test your 7 nodes deployment in kubernetes

**Comment by Jean-Baptiste-Lasselle** [comment]
# K8s 

https://github.com/smilofoundation/kubernetes-smilo#create-smilo-deployment

* create my cluster :  (more tomorrow) https://github.com/pokusio/k3s-topgun

**Comment by Jean-Baptiste-Lasselle** [comment]
* install docker, kubectl, k3d, 
* launch cluster : 
```bash
jbl@pegasusio:~$ k3d delete cluster topgunCluster
INFO[0000] Deleting cluster 'topgunCluster'             
INFO[0000] Deleted k3d-topgunCluster-masterlb           
INFO[0000] Deleted k3d-topgunCluster-worker-4           
INFO[0001] Deleted k3d-topgunCluster-worker-3           
INFO[0002] Deleted k3d-topgunCluster-worker-2           
INFO[0002] Deleted k3d-topgunCluster-worker-1           
INFO[0003] Deleted k3d-topgunCluster-worker-0           
INFO[0003] Deleted k3d-topgunCluster-master-2           
INFO[0003] Deleted k3d-topgunCluster-master-1           
INFO[0004] Deleted k3d-topgunCluster-master-0           
INFO[0004] Deleting cluster network '3b19afa809622c905ad0da66fe2bcbe853a601f00348455616c8ce6aea1d2d1b' 
INFO[0004] Deleting image volume 'k3d-topgunCluster-images' 
INFO[0004] Removing cluster details from default kubeconfig 
INFO[0004] Successfully deleted cluster topgunCluster!  
jbl@pegasusio:~$ k3d create cluster --k3s-server-arg "k3s server --tls-san \"pegasusio.io\"" topgunCluster --masters 1 --workers 9
INFO[0000] Created network 'k3d-topgunCluster'          
INFO[0000] Created volume 'k3d-topgunCluster-images'    
INFO[0001] Creating node 'k3d-topgunCluster-master-0'   
INFO[0001] Creating node 'k3d-topgunCluster-worker-0'   
INFO[0002] Creating node 'k3d-topgunCluster-worker-1'   
INFO[0003] Creating node 'k3d-topgunCluster-worker-2'   
INFO[0003] Creating node 'k3d-topgunCluster-worker-3'   
INFO[0004] Creating node 'k3d-topgunCluster-worker-4'   
INFO[0005] Creating node 'k3d-topgunCluster-worker-5'   
INFO[0006] Creating node 'k3d-topgunCluster-worker-6'   
INFO[0006] Creating node 'k3d-topgunCluster-worker-7'   
INFO[0007] Creating node 'k3d-topgunCluster-worker-8'   
INFO[0008] Creating LoadBalancer 'k3d-topgunCluster-masterlb' 
INFO[0010] Cluster 'topgunCluster' created successfully! 
INFO[0010] You can now use it like this:                
export KUBECONFIG=$(k3d get kubeconfig topgunCluster)
kubectl cluster-info
jbl@pegasusio:~$ export KUBECONFIG=$(k3d get kubeconfig topgunCluster)
jbl@pegasusio:~$ kubectl get all
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.43.0.1    <none>        443/TCP   47s
jbl@pegasusio:~$ kubectl get all,nodes
NAME                 TYPE        CLUSTER-IP   EXTERNAL-IP   PORT(S)   AGE
service/kubernetes   ClusterIP   10.43.0.1    <none>        443/TCP   79s

NAME                              STATUS   ROLES    AGE   VERSION
node/k3d-topguncluster-worker-0   Ready    <none>   43s   v1.18.4+k3s1
node/k3d-topguncluster-worker-3   Ready    <none>   43s   v1.18.4+k3s1
node/k3d-topguncluster-worker-7   Ready    <none>   42s   v1.18.4+k3s1
node/k3d-topguncluster-worker-2   Ready    <none>   42s   v1.18.4+k3s1
node/k3d-topguncluster-master-0   Ready    master   41s   v1.18.4+k3s1
node/k3d-topguncluster-worker-5   Ready    <none>   41s   v1.18.4+k3s1
node/k3d-topguncluster-worker-6   Ready    <none>   43s   v1.18.4+k3s1
node/k3d-topguncluster-worker-1   Ready    <none>   42s   v1.18.4+k3s1
node/k3d-topguncluster-worker-4   Ready    <none>   42s   v1.18.4+k3s1
node/k3d-topguncluster-worker-8   Ready    <none>   41s   v1.18.4+k3s1
jbl@pegasusio:~$ 
```
* run the exact instructions first (hum i don't like switching contexts with `kubectl`, cause of infra as code nevermind not important...) : 

```bash
export YOUR_NAMESPACE="smilo-test"
kubectl config set-context $(kubectl config current-context) --namespace=$YOUR_NAMESPACE

# like https://github.com/smilofoundation/kubernetes-smilo#create-smilo-deployment
git clone git@github.com:smilofoundation/kubernetes-smilo ./smilo-boxies
cd  ./smilo-boxies
kubectl apply -f 7nodes/smilobft-7nodes-blackbox/k8s-yaml/
sleep 5s
kubectl get pods --all-namespaces
```
* Results (**big failure**) : 

```bash 
jbl@pegasusio:~$ # like https://github.com/smilofoundation/kubernetes-smilo#create-smilo-deployment
jbl@pegasusio:~$ git clone git@github.com:smilofoundation/kubernetes-smilo ./smilo-boxies
Clonage dans './smilo-boxies'...
Warning: Permanently added the RSA host key for IP address '140.82.118.4' to the list of known hosts.
remote: Enumerating objects: 776, done.
remote: Counting objects: 100% (776/776), done.
remote: Compressing objects: 100% (413/413), done.
remote: Total 776 (delta 289), reused 776 (delta 289), pack-reused 0
Réception d'objets: 100% (776/776), 205.86 KiB | 0 bytes/s, fait.
Résolution des deltas: 100% (289/289), fait.
jbl@pegasusio:~$ cd  ./smilo-boxies
jbl@pegasusio:~/smilo-boxies$ kubectl apply -f 7nodes/smilobft-7nodes-blackbox/k8s-yaml/
unable to recognize "7nodes/smilobft-7nodes-blackbox/k8s-yaml/04-smilo-deployments.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "7nodes/smilobft-7nodes-blackbox/k8s-yaml/04-smilo-deployments.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "7nodes/smilobft-7nodes-blackbox/k8s-yaml/04-smilo-deployments.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "7nodes/smilobft-7nodes-blackbox/k8s-yaml/04-smilo-deployments.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "7nodes/smilobft-7nodes-blackbox/k8s-yaml/04-smilo-deployments.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "7nodes/smilobft-7nodes-blackbox/k8s-yaml/04-smilo-deployments.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
unable to recognize "7nodes/smilobft-7nodes-blackbox/k8s-yaml/04-smilo-deployments.yaml": no matches for kind "Deployment" in version "extensions/v1beta1"
jbl@pegasusio:~/smilo-boxies$ 
jbl@pegasusio:~/smilo-boxies$ kubectl get all,nodes
NAME                              STATUS   ROLES    AGE   VERSION
node/k3d-topguncluster-worker-3   Ready    <none>   17m   v1.18.4+k3s1
node/k3d-topguncluster-worker-6   Ready    <none>   17m   v1.18.4+k3s1
node/k3d-topguncluster-worker-0   Ready    <none>   17m   v1.18.4+k3s1
node/k3d-topguncluster-worker-4   Ready    <none>   17m   v1.18.4+k3s1
node/k3d-topguncluster-worker-7   Ready    <none>   17m   v1.18.4+k3s1
node/k3d-topguncluster-worker-1   Ready    <none>   17m   v1.18.4+k3s1
node/k3d-topguncluster-worker-2   Ready    <none>   17m   v1.18.4+k3s1
node/k3d-topguncluster-master-0   Ready    master   17m   v1.18.4+k3s1
node/k3d-topguncluster-worker-8   Ready    <none>   17m   v1.18.4+k3s1
node/k3d-topguncluster-worker-5   Ready    <none>   17m   v1.18.4+k3s1
jbl@pegasusio:~/smilo-boxies$ 

```
* opened an issue : https://github.com/smilofoundation/kubernetes-smilo/issues/1 @thomasmodeneis 

* also a question : https://github.com/smilofoundation/go-smilo i relly hope that this is not just the `geth` client...

**Comment by Jean-Baptiste-Lasselle** [comment]
@thomasmodeneis ... Heum i find today somtething I really did not like : 

* https://github.com/jpmorganchase/qubernetes#qubernetes
* In your documentation you talk about a 7 nodes deployment... I won't ask "Are you kidding me ?", but i'm getting close to here...
* https://github.com/jpmorganchase/qubernetes/blob/master/docs/7nodes-on-k8s.md ....???

Ok, I am closing your proposal, it is completely dismissed : 
* what you gave just does not work
* you have  a repo with just one star: and you stared it yourself (come on, was that ncessary, honestly ?...) 
* and now I find that you just copy pasted some other people's work ...? You know It's JP Morgan Chase, what's gonna happen If I contact them and tell them you use their work without mentionning them as authors ...?
* All in all, I really do not appreciate at all, and you still can answer on this issue

For now, KO for you.
